esc 退出编辑模式

m 变为md模式

shift/ctrl + enter 恢复md显示

enter 进入编辑模式

b （向下）新建一个cell

d d 删除当前cell

# ndarray

## 入门

In [1]:
import torch

`torch.arange(n)`

创建一个从0到n-1的向量，默认创建为整数。也可指定创建类型为浮点数。

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过tensor的`shape`属性来访问张量（沿每个轴的长度）的形状

In [3]:
x.shape

torch.Size([12])

如果只想知道张量中元素的总数，即形状的所有元素乘积，可以检查它的大小（size）。

In [4]:
x.numel()

12

要想改变一个张量的形状而不改变元素数量和元素值，可以调用`reshape`函数。

注：可以通过`-1`来调用此自动计算出维度的功能。

In [5]:
x2 = x.reshape(3, 4)
x2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
x3 = x.reshape(-1, 4)
x3

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
x4 = x.reshape(3, -1)
x4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

`torch.zeros(...)`

生成**全0**的tensor，一般用于初始化矩阵

In [8]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

`torch.ones(...)`

生成**全1**的tensor，一般用于初始化矩阵

In [9]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

张量中每个元素的值也可以通过从某个特定的概率分布中随机采样得到。

`torch.randn(...)`

每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样。


In [11]:
torch.randn(3, 4)

tensor([[ 0.4576,  0.3486,  0.5026, -0.3907],
        [-1.3482, -0.3349,  0.4526, -0.5706],
        [-0.8101, -2.0379,  0.4522, -1.1677]])

In [12]:
torch.randn((3,4))

tensor([[ 0.2303, -0.4891, -0.0785, -0.7408],
        [-0.3140, -1.1735, -0.2338, -0.0529],
        [-1.0651,  1.1312,  1.4806,  0.4982]])

可以通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值。


In [13]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 运算符

对于任意**具有相同形状**的张量，
**常见的标准算术运算符（`+`、`-`、`*`、`/`和`**`）**都可以被升级为**按元素运算**。

注：使用逗号来表示一个具有5个元素的元组，其中每个元素都是按元素操作的结果。

In [15]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

**求幂** `exp()`也可以按元素计算。


In [16]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

可以把多个张量**连接**（concatenate） `cat(tuple of Tensors, dim)`在一起，形成一个更大的张量。

需要提供张量列表，并给出沿哪个轴连结。


In [17]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过**逻辑运算符**构建二元张量。

以`X == Y`为例：对于每个位置，如果`X`和`Y`在该位置相等，则新张量中相应项的值为1。


In [20]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行**求和**，会产生一个**单元素张量(没有shape)**。


In [21]:
S = X.sum()
S

tensor(66.)

In [22]:
S.shape

torch.Size([])

In [23]:
S.numel()

1

## 广播机制



在某些情况下，即使**形状不同**，我们仍然可以通过调用**广播机制（broadcasting mechanism）**来执行**按元素操作**。
这种机制的工作方式如下：

1. 通过适当**复制元素**来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；

2. 对生成的数组执行按元素操作。

In [24]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

由于`a`和`b`分别是$3\times1$和$1\times2$矩阵，如果让它们相加，它们的形状不匹配。
我们将两个矩阵*广播*为一个更大的$3\times2$矩阵，如下所示：矩阵`a`将复制列，
矩阵`b`将复制行，然后再按元素相加。


In [25]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

**错误示范1**：$3\times1$ 加 $2\times1$
``` python
c = torch.arange(3).reshape((3,1))
d = torch.arange(2).reshape((2,1))
c + d
```

**错误示范2**：$3\times1\times2$ 加 $2\times2\times1$
``` python
c = torch.arange(6).reshape((3, 1, 2))
d = torch.arange(4).reshape((2, 2, 1))
c + d
```

## 索引和切片

张量中的元素可以通过**索引访问**。

第一个元素的索引是`0`，最后一个元素索引是`-1`；

指定范围包含第一个元素和最后一个**之前**的元素。

In [36]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
X, X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

可以通过**指定索引**来将元素**写入**矩阵。


In [37]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

如果我们想**为多个元素赋值相同的值**，我们只需要索引所有元素，然后为它们赋值。

“:”代表沿轴的所有元素。

适用于向量和超过2个维度的张量。

In [38]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 节省内存

运行一些操作可能会**导致为新结果分配内存**

例如，如果我们用`Y = X + Y`，我们将取消引用`Y`指向的张量，而是**指向新分配的内存处的张量**。
运行`Y = Y + X`后，我们会发现`id(Y)`指向另一个位置。
这是因为Python首先计算`Y + X`，为结果分配新的内存，然后使`Y`指向内存中的这个新位置。

Python的`id()`函数提供了内存中引用对象的确切地址。



In [39]:
before = id(Y)
Y = Y + X
id(Y) == before

False

这可能是**不可取的**，原因有两个：

1. 首先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。通常情况下，我们**希望原地执行这些更新**；
2. 如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码**可能会无意中引用旧的参数**。


**执行原地操作**:

使用**切片表示法**将操作的结果分配给先前分配的数组，例如`Y[:] = <expression>`。

使用`zeros_like`来分配一个全$0$的块，形状与Y相同。


In [49]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140391485328416
id(Z): 140391485328416


In [50]:
print('id(Y):', id(Y))
Y[:] = X + Y
print('id(Y):', id(Y))

id(Y): 140391485326176
id(Y): 140391485326176


如果在后续计算中**没有重复使用`X`**，
我们也可以使用`X[:] = X + Y`或`X += Y`来减少操作的内存开销。


In [47]:
before = id(X)
X += Y
id(X) == before

True

## 转换为其他Python对象


torch张量和numpy数组很容易相互转换，

torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量。

In [2]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
A = X.numpy()
B = torch.tensor(A)
print(type(A), type(B))
print("id(X):", id(X))
print("id(A):", id(A))
print("id(B):", id(B))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
id(X): 140091616366240
id(A): 140091603189360
id(B): 140095596149392


In [8]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
print(X)
X[0, 0] = 12
A[0, 1] = 13
print(X)
print(A)
print(B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
[[12. 13.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


要(**将大小为1的张量转换为Python标量**)，我们可以调用`item`函数或Python的内置函数。


In [24]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 小结

* 深度学习存储和操作数据的主要接口是张量（$n$维数组）。它提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换其他Python对象。

## 练习

1. 运行本节中的代码。将本节中的条件语句`X == Y`更改为`X < Y`或`X > Y`，然后看看你可以得到什么样的张量。
1. 用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？


[Discussions](https://discuss.d2l.ai/t/1747)
